### ISSUE TITLE
Downloading as .py fails

### ISSUE THREAD

**Issue by rbiswas4** [jupyter/jupyter_core#1]
Not sure if this is the right location, but I upgraded ipython notebook to version 3.0 using anaconda and 
therefore using jupiter. 
```
 ipython notebook --version
3.0.0
```
I am on a mac running OS X version 10.10.2

When I try using the toolbar to download the notebook as a python file, or html or rst or pdf, I get a page 
saying 
```
500: Internal Server Error 
the error was 
Could not import nbconvert: No module named mistune
```

Thanks for help in advance

**Comment by takluyver** [comment]
Try `pip install mistune`.

Bugs should still be filed at https://github.com/ipython/ipython for now. We're in the process of splitting up the repo, so there will be new repositories like jupyter_notebook and jupyter_nbconvert for now.
