### ISSUE TITLE
Traitlets 4.3.1 gives me: DeprecationWarning: metadata {'config': True} was set from the constructor

### ISSUE THREAD

**Issue by tomdz** [jupyter/jupyter_core#101]
Traitlets 4.3.1 gives me this warning:
```
DeprecationWarning: metadata {'config': True} was set from the constructor.
With traitlets 4.1, metadata should be set using the .tag() method,
e.g., Int().tag(key1='value1', key2='value2')
```
Looks like it is coming from here: https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/application.py#L105-L123

**Comment by rolweber** [comment]
Some deprecations have been reverted in traitlets 4.3.2. Does that resolve this issue?
See comment https://github.com/jupyter/jupyter_client/issues/249#issuecomment-316409561 by @minrk.

**Comment by minrk** [comment]
Indeed, this is not deprecated anymore.
