### ISSUE TITLE
Traitlets 4.3.1 gives me: JupyterApp._config_dir_default is deprecated in traitlets 4.1

### ISSUE THREAD

**Issue by tomdz** [jupyter/jupyter_core#102]
Traitlets 4.3.1 gives me this warning:
```
DeprecationWarning: JupyterApp._config_dir_default is deprecated in traitlets 4.1
```
(the `_should_warn` key has `use @default decorator instead` in it).

**Comment by rolweber** [comment]
Some deprecations have been reverted in traitlets 4.3.2. Does that resolve this issue?
See comment https://github.com/jupyter/jupyter_client/issues/249#issuecomment-316409561 by @minrk.

**Comment by minrk** [comment]
Yup
