### ISSUE TITLE
jupyter subcommands should be discoverable in help message

### ISSUE THREAD

**Issue by ricklupton** [jupyter/jupyter_core#11]
`ipython --help` shows a list of possible subcommands, whereas with the jupyter command it's hard to see what is available:

```console
$ jupyter --help                    
usage: jupyter [-h] subcommand

Jupyter: Interactive Computing

positional arguments:
  subcommand  The subcommand to launch

optional arguments:
  -h, --help  show this help message and exit
```

I guess it's not trivial to list the subcommands, since they are all separate programs, but it would make it easier to use.

**Comment by ricklupton** [comment]
This shows `install` not `install-nbextension`. Are there actually any sub-sub-commands which need to be removed from the list? If not, #15 fixes this example.

```
Available subcommands: install notebook kernelspec nbconvert trust
```

**Comment by kidpixo** [comment]
Hi, 
I wrote a completion script for jupyter subcommands for the fish shell
Raw https://gist.github.com/kidpixo/055edb0f3bf1ddba25013c591c079545
