### ISSUE TITLE
Possible to ignore System and User kernelspec files?

### ISSUE THREAD

**Issue by habemus-papadum** [jupyter/jupyter_core#114]
Hi -- I'm interested in creating a self contained/isolated jupyter. The locations jupyter looks for kernelspecs are described here: http://jupyter-client.readthedocs.io/en/latest/kernels.html

It is possible to launch `jupyter notebook` etc such that it ignores kernel specs in the user and system directories, but instead only takes specs found in sys.prefix?

thanks, nehal

**Comment by Carreau** [comment]
HI @habemus-papadum, 

If you look the [KernelSpecManager](https://github.com/jupyter/jupyter_client/blob/f40dcd327be188ca8b8f12e24c5585a0eaca039c/jupyter_client/kernelspec.py#L136-L153), subclass it, set kernel_dirs to what you are looking for, and set this as the kernelspec manager for the notebook server; then your users should only see the kernels you desire. 

Now, I would be really careful, this will likely not prevent a determined user to spawn a kernelspec of their choice, it would mostly make this harder and not show the kernels in the UI. 

If you need isolation for security then you should likely not rely on limitation of kernelspec, that will not be sufficient you most likely want to investigate JupyterHub.

**Comment by habemus-papadum** [comment]
thanks -- I was looking for "isolation for simplicity" rather than "isolation for security,"  so your advise is perfect.  Cheers.
