### ISSUE TITLE
jupyter-notebook does not exist in /usr/local/bin after doing a pip install jupyter on MAC

### ISSUE THREAD

**Issue by tusharjagtap** [jupyter/jupyter_core#116]
[/usr/local/bin]› ls -l | grep jupyter
-rwxr-xr-x  1 root      admin                222 Oct 17 16:02 jupyter
-rwxr-xr-x  1 root      admin                222 Oct 17 16:02 jupyter-migrate
-rwxr-xr-x  1 root      admin                227 Oct 17 16:02 jupyter-troubleshoot
-rwxr-xr-x  1 root      admin                255 Oct 17 16:02 jupyter-trust

Why isnt there any jupyter-notebook?

Hence, when i try to run "pupyter notebook" command, I get an error "Error executing Jupyter command 'notebook': [Errno 2] No such file or directory"

**Comment by takluyver** [comment]
`pip install jupyter` should have installed everything, but try `pip install notebook`; if it tells you it's already installed, where does it say it's installed to?

**Comment by mattshma** [comment]
@tusharjagtap 
> Since you are doing --user installs on macOS, scripts are going in `$HOME/Library/Python/2.7/bin`. which needs to be on your PATH and isn't by default. If that's the case, you can add it with:
```
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
```
>which you can add to ~/.bashrc.

Link: https://stackoverflow.com/questions/42526179/jupyter-notebook-is-not-a-jupyter-command

**Comment by kikacaty** [comment]
Running `python -m notebook` works for me.
