### ISSUE TITLE
Bash completion file crashes gnome-terminal

### ISSUE THREAD

**Issue by AntoniosHadji** [jupyter/jupyter_core#121]
When I drop the `examples/jupyter-completion.bash` from the master branch in `/etc/bash_completion.d/` gnome-terminal crashes when typing `jupyter con` followed by hitting the tab key.

expected behavior is completion of `jupyter console`
startup of `jupyter console` command shows:
```
Jupyter console 5.1.0

Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
```

Environment:
```
python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/antonios/.local/lib/python3.5/site-packages/IPython',
 'ipython_version': '6.1.0',
 'os_name': 'posix',
 'platform': 'Linux-4.11.0-kfd-compute-rocm-rel-1.6-180-x86_64-with-Ubuntu-16.04-xenial',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Sep 14 2017, 22:51:06) \n[GCC 5.4.0 20160609]'}
```

**Comment by takluyver** [comment]
I've marked this 'help wanted' - I don't think any of us are very familiar with the bash completion system, so it would be great if someone else could investigate.

**Comment by andram** [comment]
There was a problem, when the bash-completion code was adapted from ipython. I have fixed this in pull request #125

**Comment by takluyver** [comment]
Thanks @andram !

@AntoniosHadji does @andram's PR fix it for you?

**Comment by andram** [comment]
Thanks for merging. I had a further look at the bash completion code and discovered two more inconsistencies. Please consider also merging pull request #126 to allow for correct file name completion and options without subcommands.

**Comment by takluyver** [comment]
Thanks @andram . I'm assuming this issue is fixed now.
