### ISSUE TITLE
Autocomplete list is duplicated in jupyter notebook and consoles

### ISSUE THREAD

**Issue by wikiped** [jupyter/jupyter_core#124]
This:
![](https://camo.githubusercontent.com/1da165be27da107cf1c77738222e8fe5dd253782/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f6e673676322e706e67)

Happens in notebook, console and qtconsole.

But it does not happen in ipython terminal - no duplicates there.

Versions (on win10x64):

    jupyter              1.0.0     py36_0    conda-forge
    jupyter_client       5.2.1     py36_0    conda-forge
    jupyter_console      5.2.0     py36_0    conda-forge
    jupyter_core         4.4.0     py36_0    conda-forge
                                 
    ipython              6.2.1     py36_1    conda-forge
    ipython_genutils     0.2.0     py36_0    conda-forge

Downgrading `jupyter_core` (down to `4.0.2`) does not help.

Downgrading ipython to 5.5.0 "fixes" the issue.

Linked [issue](https://github.com/jupyter/notebook/issues/3238)

**Comment by takluyver** [comment]
This is actually a bug in IPython, not in jupyter_core - see https://github.com/ipython/ipython/pull/10969

**Comment by data83** [comment]
Solution:

`pip uninstall jedi`
