### ISSUE TITLE
ImportError: dateutil 2.5.0 is the minimum required version

### ISSUE THREAD

**Issue by ijhajj** [jupyter/jupyter_core#137]
I installed pandas_datareader and started encountering this error when I try to import pandas in Python3. 
It works fine for python2 version in Jupyter.
I checked the import statement directly in terminal, and all looks fine. Makes me think its something to do with the version Jupyter is picking up with Python3.
I double checked the dateutil and I do have the 2.7.3 version on my system.
Can you please suggest how to resolve the issue!?

Details:
 ImportError                               Traceback (most recent call last)
<ipython-input-1-7dd3504c366f> in <module>()
----> 1 import pandas as pd

~/.local/lib/python3.5/site-packages/pandas/__init__.py in <module>()
     21 
     22 # numpy compat
---> 23 from pandas.compat.numpy import *
     24 
     25 try:

~/.local/lib/python3.5/site-packages/pandas/compat/__init__.py in <module>()
    420 
    421 if LooseVersion(dateutil.__version__) < LooseVersion('2.5'):
--> 422     raise ImportError('dateutil 2.5.0 is the minimum required version')
    423 from dateutil import parser as _date_parser
    424 parse_date = _date_parser.parse

ImportError: dateutil 2.5.0 is the minimum required version

**Comment by pjshort** [comment]
I had this same issue using the newest pandas version - downgrading to pandas 0.22.0 fixes the problem. 

I am not using Jupyter, so I think this is likely a pandas problem, not a jupyter problem!

**Comment by sanjibsur11** [comment]
It gives same error even after downgrading to pandas 0.22.0 under Ubuntu 18.04.

**Comment by Alilino** [comment]
Downgrading worked for me too! Thanks

**Comment by goraniliev** [comment]
I encounter the same issue on `Python 2.7`. I have `python-dateutil==2.7.5` and the error is `ImportError: dateutil 2.5.0 is the minimum required version`.

**Comment by bacondanbin** [comment]
Downgrading didn't work for me.
I have python-dateutil==2.7.5 and pandas==0.22.0 in ubuntu 18.04 using python2.7
Is there any solution to fix the problems?

**Comment by takluyver** [comment]
Closing because this is not a Jupyter issue, but feel free to continue sharing tips here if it helps you.

**Comment by 98yangjames** [comment]
Nothing here is helpful
