### ISSUE TITLE
Inconsistent Jupyter data directories in documentation

### ISSUE THREAD

**Issue by Varal7** [jupyter/jupyter_core#138]
I have noticed some surprising behavior while trying to modify my Jupyter Data directory.

From #46, I understood that data files, runtime files and configuration files should be in three different directories, and that this can be observed using `jupyter --paths`

The [documentation](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html) indicates that I should set the variable `JUPYTER PATH`.

Indeed, I observe the expected behavior:

```
 $ jupyter --paths
config:[...]
data:
    /home/varal7/.local/share/jupyter
    /scratch/varal7/miniconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
$ JUPYTER_PATH=/scratch/varal7/local/share/jupyter jupyter --paths
config:[...]
data:
    /scratch/quach/local/share/jupyter
    /home/varal7/.local/share/jupyter
    /scratch/varal7/miniconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
```

However, when running a notebook, the files are still saved in `/home/varal7/.local/share/jupyter`.

Moreover, 

```
$ JUPYTER_PATH=/scratch/varal7/local/share/jupyter jupyter --data-dir
/home/varal7/.local/share/jupyter
```

Finally, I have come to understand that the correct variable to set is actually `JUPYTER_DATA_DIR` as I could see in:

```
$ JUPYTER_DATA_DIR=/scratch/quach/local/share/jupyter jupyter --data-dir
/scratch/quach/local/share/jupyter
```

This is consistent with documentation I later found here: https://jupyter-core.readthedocs.io/en/latest/paths.html

**Comment by louisabraham** [comment]
I can confirm this behavior.

**Comment by takluyver** [comment]
I think `JUPYTER_DATA_DIR` should be added to the documentation page in your first link. The source for those docs is in the [jupyter/jupyter repo](https://github.com/jupyter/jupyter).

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. I believe this was fixed by https://github.com/jupyter/jupyter/pull/450

Thanks everyone and happy hacking! :bowtie:
