### ISSUE TITLE
FeatureRequest: Please support latex style cross referencing

### ISSUE THREAD

**Issue by parthi2929** [jupyter/jupyter_core#140]
Hi

For my project, I write both raw tex file directly and also ipython files which I later convert to tex and compile both as chapters for final pdf. Due to information dependency, I sometimes have to refer equation in raw tex file from ipython notebook. If it had been another tex file, I could have used ```\externaldocument``` option, but I could not find any equivalent in ipython to do that. I see Mathjax supports ```\ref``` but the part referencing should be in the same file. So afaik, I could not find any way to achieve cross referencing in ipython. 

Can you please let me know if there is still any way or workaround to do this? If not, can you kindly consider implementing. 

Since ipython is wonderful for literate programming, it is becoming more and more friendlier choice for academic journals, so support for such latex functionalities becomes highly desirable. Kindly consider the request.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one, as it does not apply to the jupyter_core project. Anyone wanting to more details about converting notebooks to PDF should probably search around on the nbconvert repository, for example https://github.com/jupyter/nbconvert/issues/828 has some relevant discussion.

Thanks everyone and happy hacking! :bowtie:
