### ISSUE TITLE
Jupyter "Error executing Jupyter command 'notebook': [Errno 'jupyter-notebook' not found] 2"

### ISSUE THREAD

**Issue by bavalpey** [jupyter/jupyter_core#141]
I have been racking my brain over this issue, but I am having problems opening jupyter from the command prompt. Specifically, it seems that jupyter commands are broken. I am unable to type anything after jupyter with a space, or I receive the error message: "Error executing Jupyter command 'Searches': [Errno 'jupyter-Searches' not found] 2"

Note, that this is _not_ a problem with it not recognizing jupyter from the path.  I am able to get the notebook to open by typing jupyter-notebook.  However, I am confused as to why all jupyter commands are broken.  I have tried reinstalling both jupyter and my entire python installation, but to no avail.

I installed jupyter from the commandline using pip install  --force-reinstall --no-cache-dir jupyter.

The only weird error I get when running this is:

ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.

**Comment by bavalpey** [comment]
https://jupyter.readthedocs.io/en/latest/projects/jupyter-command.html

Basically, this functionality is broken.

**Comment by bavalpey** [comment]
This is preventing me from installing new kernels. For instance, I am unable to run the command from R: IRkernel::installspec().
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 1.
In addition: Warning message:
running command '"jupyter" kernelspec --version' had status 1

**Comment by ivanov** [comment]
Very sorry you ran into this @bavalpey (and sorry it took so long for us to get back to you). Hopefully you've gotten it sorted out.

I'm going through old issues and it seems to me that it makes sense to close this one. If anyone comes across this, there are others who dealt with similar symptoms on #84 - so perhaps give that thread a read.

Thanks again for your report, @bavalpey and happy hacking! :bowtie:
