### ISSUE TITLE
Mutating environ PATH's side effects

### ISSUE THREAD

**Issue by mlucool** [jupyter/jupyter_core#145]
Hi,

To ensure the right subcommand is launched, Jupyter is mutating the path. [https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/command.py#L116](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/command.py#L116)

Can we undo this before any Kernel is launched? Otherwise the juptyer subcommands still take precedence when you do something in a subprocess from inside any kernel. This effect can be seen when you check `os.environ['PATH']` in any kernel. Aside from naming conflicts for jupyter commands, this overwrites the version of python in the path to the one you launched the jupyter server with. This is a problem when you want your path to default to python 2, but run the newest jupyter server, which requires python 3.

Please let me know if you need more info.

Thanks!

**Comment by xmnlab** [comment]
comments on jupyterlab gitter about this by @kevin-bates 

```
@xmnlab - kernel launches occur within jupyter_client in launch_kernel() by way of start_kernel() of the kernel manager which can manipulate the env prior to launch.
```
it seems we should check jupyter_client, maybe we should resolve this issue into there.

**Comment by xmnlab** [comment]
I am also taking a look into `jupyter_core/application.py::JupyterApp::launch_instance`
