### ISSUE TITLE
jupyter notebook password `No such file or directory: <path>/password`

### ISSUE THREAD

**Issue by bunchoftrees** [jupyter/jupyter_core#151]
Hey all, I followed directions here (https://lib.smgr.io/remote-jupyter-notebook-server/) to get Jupyter up and running on a web server with apache 2. When I run `jupyter notebook password` to set my password, I get this error: `[C 20:02:20.025 NotebookApp] No such file or directory: /home/<username>/password`

Thoughts?

**Comment by takluyver** [comment]
It's possible you need a newer version of the `notebook` package. If you need to, please create follow-up issues on the jupyter/notebook repo: https://github.com/jupyter/notebook.
