### ISSUE TITLE
Creating Jupyter Notebook Failed - An error occurred while creating a new notebook.

### ISSUE THREAD

**Issue by viky035** [jupyter/jupyter_core#152]
Hi, guys! The Jupyter does not let me create a new file. I have tried many methods but failed. I could create a new file normally before, but it suddenly didn't work. Then, I reinstalled the Anaconda for many times but the problem is still here.

![image](https://user-images.githubusercontent.com/51168856/58571346-1dd3a800-826c-11e9-86e2-c98c354b905e.png)

![image](https://user-images.githubusercontent.com/51168856/58571399-3a6fe000-826c-11e9-8a59-915973406b5e.png)

Hope you could help me! Thanks!

**Comment by takluyver** [comment]
I suspect that the directory in which you were trying to create notebooks has been deleted.

If not, please post an issue on the jupyter/notebook repository: https://github.com/jupyter/notebook
