### ISSUE TITLE
Change jupyter -h usage example.

### ISSUE THREAD

**Issue by jdfreder** [jupyter/jupyter_core#16]
`jupyter -h` yields

```
usage: jupyter [-h] subcommand

Jupyter: Interactive Computing

positional arguments:
  subcommand  The subcommand to launch

optional arguments:
  -h, --help  show this help message and exit

Available subcommands: kernelspec nbconvert trust install notebook qtconsole
console
```

which is deceptive, because `jupyter -h subcommand` just yields the same message.  To get the help for a subcommand to display, one has to run `jupyter subcommand -h`.  The cause of this deceptive output appears to be argparser.

**Comment by minrk** [comment]
Hm. Argparse makes that output. I'm not sure what the best way to change it is.

**Comment by takluyver** [comment]
The output now looks like this:

```
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
...
```

It doesn't technically show that the options are mutually exclusive, but I think it's less misleading now than it was when this issue was opened.

**Comment by jdfreder** [comment]
Yes, that is better.
