### ISSUE TITLE
jupyter bash completion OS X compatibility

### ISSUE THREAD

**Issue by alexisdimi** [jupyter/jupyter_core#168]
The current version of jupyter bash completion (`examples/jupyter-completion.bash`, see [Issue #121](https://github.com/jupyter/jupyter_core/issues/121)), uses a bash 4.x feature and will not work on OS X, which comes with bash version 3.2. 

**Resolution:** It is very easy to fix this and achieve bash 3.2 compatibility: Just rewrite these two lines near the end of the file, from

    <        compopt -o filenames
    <        COMPREPLY=( $(compgen -f -- ${cur}) )
to simply

    >        COMPREPLY=( $(compgen -o filenames -f -- ${cur}) )

This achieves precisely the same behavior without involving the troublesome command `compopt`.

**Comment by willingc** [comment]
Closed by #169
