### ISSUE TITLE
[feature request] Adding cells with other lightweight markup languages 

### ISSUE THREAD

**Issue by Foadsf** [jupyter/jupyter_core#170]
Reading [this Reddit post](https://www.reddit.com/r/Python/comments/33kyta/question_jupyter_and_restructuredtext/) and [this closes issue](https://github.com/jupyter/help/issues/241), I still think it would be great to have cells with different lightweight markup languages such as AsciiDoc, reStructuredText, MathML HTML-CSS-JS, and even the more advanced flavors of MarkDown such as MultiMarkDown and Rmarkdown. I don't know exactly about the reST, but AsciiDoc at least has live preview extensions for almost all Electron-based browsers/editors out there. This could be really beneficial for documentation and even presentations (e.g., [this Reddit post](https://www.reddit.com/r/writing/comments/b0ywcw/free_markdown_editors_with_live_preview_for/)). I have read some of the discussions from the past about the difficulty of implementing reStructuredText, but technology has changed, and IMHO this idea deserves to be at least in the long term horizon if not an immediate feature request. Thanks for your support in advance.

**Comment by willingc** [comment]
Thanks @Foadsf for sharing your interest in more markup languages. JupyterLab is very extensible. I recommend following its development and extension development. Here's an issue that addresses the suggested enhancement approach: https://github.com/jupyterlab/jupyterlab/issues/3896
