### ISSUE TITLE
How does jupyter preview the video? 

### ISSUE THREAD

**Issue by pick56** [jupyter/jupyter_core#175]
How does jupyter preview the video? My data is a lot of videos, but when I open it with jupyter, the browser opens a new window, but it can't be played. Can this be solved?

**Comment by Zsailer** [comment]
Hi @pick56. Thanks for the question.

This question is a bit unrelated to `jupyter_core`, though I totally understand why you would post here. The name, jupyter_core, is a bit deceiving. This is a low-level Python library used by various Jupyter-related applications, e.g. Jupyter Notebook or JupyterLab.

I suggest redirecting your question to the [Jupyter Discourse](https://discourse.jupyter.org/) page. You'll likely get a lot more help there.
