### ISSUE TITLE
ImportError: cannot import name secure_write

### ISSUE THREAD

**Issue by shinokada** [jupyter/jupyter_core#179]
I run Jupyter on macOS Catalina, version 10.15.2.
The following is my jupyter version and debug outputs.

As you can see in the last line I get `ImportError: cannot import name secure_write`.

```
jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.2.3
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

jupyter notebook --debug
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 81, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "/usr/local/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 19, in <module>
    from jupyter_client.session import Session
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/python2.7/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name secure_write
```

The following is my jupyter --path

```
jupyter --path
config:
    /Users/shinokada/.jupyter
    /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/shinokada/Library/Jupyter
    /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/shinokada/Library/Jupyter/runtime
```

What can I do to eliminate the error?

**Comment by kevin-bates** [comment]
This strikes me as being related to differing python versions. For example, the traceback above shows python 2.7 in play, while the `jupyter --path` output intimates python 3.7.

The version stamps from `jupyter --version` look correct, but perhaps those too are relative to 3.7 and you might have an older `jupyter_core` in your 2.7 env - one older than `4.6.0` at least (at which time `secure_write` was moved from client to core).

I would confirm your 2.7 env has the appropriate version of `jupyter_core` and `jupyter_client`.

**Comment by kalanaej** [comment]
j

**Comment by kalanaej** [comment]
Same question asked on [https://github.com/jupyter/jupyter_core/issues/179](here). I think you can find your answer from there

**Comment by tom-doerr** [comment]
I think @kalanaej wanted to link to https://github.com/jupyter/notebook/issues/5014 .
