### ISSUE TITLE
Feature request: better support for changing text color in markdown

### ISSUE THREAD

**Issue by gpetty** [jupyter/jupyter_core#189]
I use Jupyter notebooks for class assignments and frequently add comments in the graded versions I send back.  The use of color seems to be the best way to distinguish my comments from the original markdown text provided by the students.  As far as I can tell at least, the only way to change text color in markdown is using HTML tags, like

\<font color=red\>My comments.\</font\>

This works, but it's annoyingly verbose when I need to repeat this numerous times in each of dozens of assignments.  I would love to see much shorter tags to delimit color changes and/or a way to modify text color by highlighting a section and choosing a color option.

**Comment by jasongrout** [comment]
>  I would love to see much shorter tags to delimit color changes

I don't think we are open to changing the markdown format language

>  way to modify text color by highlighting a section and choosing a color option.

That sounds like an excellent idea!

In JupyterLab, there has also been discussion of a GUI for markdown editing. For example: https://github.com/jupytercalpoly/jupyterlab-richtext-mode

**Comment by blink1073** [comment]
> Could someone with appropriate permissions please migrate this?

Looks like our friend `Meeseeksdev` has the right permissions :smile:
