### ISSUE TITLE
Load_config inconsitency.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_core#19]
Roughly, Application.load_config deal with both `self.config_file(s)` that are full path,`self.paths` and `self.config_file_name`, that are just base name. A mix of `name=full_path`, `name=base_name` etc... are passed to traitlets `Application.load_config`

**Comment by takluyver** [comment]
@Carreau we cleaned this up a bit, do you think it needs more work for 4.0?

**Comment by Carreau** [comment]
Nah, I think it's fine IIRC.
