### ISSUE TITLE
Jupyter Notebook does not load using ubuntu 18.04 LTS in windows 10

### ISSUE THREAD

**Issue by mckot** [jupyter/jupyter_core#191]
The local host does not open on any browser.
The following error is shown.
`(venv) mayankkotambkar@LAPTOP-505GIUHT:~$ jupyter notebook
[I 09:03:50.236 NotebookApp] Serving notebooks from local directory: /home/mayankkotambkar
[I 09:03:50.237 NotebookApp] The Jupyter Notebook is running at:
[I 09:03:50.237 NotebookApp] http://localhost:8888/?token=89898adb9f0c296c9713bd70532d803321580391f1f9b7d6
[I 09:03:50.238 NotebookApp]  or http://127.0.0.1:8888/?token=89898adb9f0c296c9713bd70532d803321580391f1f9b7d6
[I 09:03:50.238 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:03:50.246 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/mayankkotambkar/.local/share/jupyter/runtime/nbserver-40-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=89898adb9f0c296c9713bd70532d803321580391f1f9b7d6
     or http://127.0.0.1:8888/?token=89898adb9f0c296c9713bd70532d803321580391f1f9b7d6
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "file:///home/mayankkotambkar/.local/share/jupyter/runtime/nbse ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand`

**Comment by mckot** [comment]
jupyter-notebook also doesn't work.

**Comment by attanew** [comment]
I had the same problem as you. This is not my solution I find it [here](https://qiita.com/yusuke_konishi/items/0e1a136a6c9331290986). Thanks to Atto Yusuke_konishi.

He has two methods to fix it and and I used method 1 and it worked:
`$ jupyter notebook --NotebookApp.use_redirect_file=False`

for jupyter lab:
`$ jupyter lab --NotebookApp.use_redirect_file=False`

to make it easy to use every time:
```
$ echo "alias jn='jupyter notebook --NotebookApp.use_redirect_file=False'" >> ~/.bashrc
$ source ~/.bashrc
$ jn
```

for jupyter lab"

```
$ echo "alias jn='jupyter lab --NotebookApp.use_redirect_file=False'" >> ~/.bashrc
$ source ~/.bashrc
$ jb
```

**Comment by Proteusiq** [comment]
> I had the same problem as you. This is not my solution I find it [here](https://qiita.com/yusuke_konishi/items/0e1a136a6c9331290986). Thanks to Atto Yusuke_konishi.
> 
> He has two methods to fix it and and I used method 1 and it worked:
> `$ jupyter notebook --NotebookApp.use_redirect_file=False`
> 
> for jupyter lab:
> `$ jupyter lab --NotebookApp.use_redirect_file=False`
> 
> to make it easy to use every time:
> 
> ```
> $ echo "alias jn='jupyter notebook --NotebookApp.use_redirect_file=False'" >> ~/.bashrc
> $ source ~/.bashrc
> $ jn
> ```
> 
> for jupyter lab"
> 
> ```
> $ echo "alias jb='jupyter lab --NotebookApp.use_redirect_file=False'" >> ~/.bashrc
> $ source ~/.bashrc
> $ jb
> ```

It is easier though placing this setting in jupyter_config.py file. In that way you do not have to have alias or editing of .bashrc
```bash
# Generate jupyter_config.py if it does not exists
jupyter jupyter notebook --generate-config

# Use nano or whatever editor. I use vs code
code ${USER}/.jupyter/jupyter_notebook_config.py

# Search and uncomment `NotebookApp.use_redirect_file=True` and set it to False
NotebookApp.use_redirect_file=False
```

**Comment by eromoe** [comment]
`jupyter lab --NotebookApp.use_redirect_file=False` doesn't work , still got same error  .
What should I do ?

**Comment by ivanov** [comment]
I think you'd only run into this if you tried to set your `BROWSER` environment variable, because without it, you would either get a yellow warning message telling you "No web browser found: could not locate runnable browser." or a WSL installed webbrowser would be launched (for example, I have `w3m` and `jupyter notebook` by default will launch that in WSL.

You can find more about how to work around this issue to use the Windows browser over here: http://github.com/jupyter/notebook/issues/4594

I'm going to go ahead and close this one, as it is not a jupyter_core issue - the launched of the browser is done via the python `webbrowser` module in the jupyter-notebook subproject.

Happy hacking! :bowtie:

**Comment by dimpase** [comment]
This need not be a Windows-only problem. Basically, the browser might not have access to user's dotfiles (e.g. Firefox installed via `snap`). And then the only way around seems to be pass, in some way, e.g. as above, or in `jupyter_notebook_config.py` the parameter `NotebookApp.use_redirect_file=False` to jupyter.

Perhaps this issue should be better documented - e.g. we just spent time figuring this out:  https://groups.google.com/g/sage-support/c/22Uj6xrP8zo/m/7M4OYU3qDgAJ

**Comment by dimpase** [comment]
@ivanov Another scenario where one sees this is when jupyter is launched in crostini (a Chromeos VM); then in crostini terminal (Debian guest OS)  one sees
```
$ jupyter-notebook Untitled.ipynb 
[I 17:18:04.802 NotebookApp] Serving notebooks from local directory: /home/dimpase/foo/bar
[I 17:18:04.802 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 17:18:04.803 NotebookApp] http://localhost:8888/?token=a1afee7184e620439aafad309355c9d467ca1cf7a8642964
[I 17:18:04.803 NotebookApp]  or http://127.0.0.1:8888/?token=a1afee7184e620439aafad309355c9d467ca1cf7a8642964
[I 17:18:04.803 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:18:05.019 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/dimpase/.local/share/jupyter/runtime/nbserver-8789-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a1afee7184e620439aafad309355c9d467ca1cf7a8642964
     or http://127.0.0.1:8888/?token=a1afee7184e620439aafad309355c9d467ca1cf7a8642964
```
but in the browser (Chrome running on the ChromeOS host) one sees `ERR_FILE_NOT_FOUND`, upon trying to open
`file:///tmp/tmpounu3jr9.html` (as the host OS has no access to guest's `/tmp/`)

Whereas
```
jupyter-notebook --NotebookApp.use_redirect_file=False Untitled.ipynb 
```
works just fine.
