### ISSUE TITLE
Feature Request - QT Console / Scriptable Notes 

### ISSUE THREAD

**Issue by Sekkei** [jupyter/jupyter_core#192]
A 'cross post' from Reddit [link](https://www.reddit.com/r/AppIdeas/comments/hclyq1/scriptable_notes_app/)

The request would be a greater focus on scripting and self designed elements, in addition to an mobile app

Or to bring it in the context of Jupyter; using the QT Console as Notes. It supports scripting with UI elements. Adding a styling syntax like lisp/latex to quickly change the text formatting

The original post from Reddit:
```
An app that lets you script little things with some UI elements like
buttons, tickbox or inputbox, for everyday / often used math tasks. 
With a design like the most note apps e.g 'keep notes'

Create a Note + Formula where you can add these elements and
give them a small logic in the background.

Shell / CSV (+ Regex) like language syntax is easy to understand and
powerful enough for example create an Input box that depending on 
the buttons give different results

\*example image of further expanded idea 
https://www.dropbox.com/s/6mmn4un5qpfffhe/idea.png
```

**Comment by ivanov** [comment]
Hey there, @Sekkei ,  I'm going through old issues and it seems to me that it makes sense to close this one. I don't believe your feature request necessitates any changes to jupyter_core. I think what you're proposing might be a better fit to discuss on the [https://github.com/jupyter/qtconsole](qtconsole) repository, though you might even want to look at using something like [Kivy](https://github.com/kivy/kivy) for this.

Thank you, and happy hacking! :bowtie:
