### ISSUE TITLE
error while converting notebook to pdf

### ISSUE THREAD

**Issue by KVSSetty** [jupyter/jupyter_core#194]
on windows 10
Jupyter lab version 1.1 4
Got this error :
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
notebook.tex:459: 
notebook.tex:459: 

Any solution

**Comment by MSeal** [comment]
This looks more like an nbconvert issue: https://github.com/jupyter/nbconvert/issues/1099, https://github.com/jupyter/nbconvert/issues/1177. There's also been several imrpovements for these issues (https://github.com/jupyter/nbconvert/pull/1345) -- some of which are in the 6.0 alpha release of nbconvert.
