### ISSUE TITLE
Start Jupyter as a executable module

### ISSUE THREAD

**Issue by bkief** [jupyter/jupyter_core#198]
I think it would be a useful to start jupyter as python executable module, for example on Windows
`py -m jupyter start` or `py -3.7 -m jupyter lab` 
This would also make using different venv easy. I think all this would require is changing the jupyter package to actually be a package with a simple \_\_main\_\_.py file added. I would be happy to contribute the PR if there is some consensus on this.

**Comment by ivanov** [comment]
Thanks for your report-  but I believe this is already the case (with the caveat that `start` is not a valid jupyter subcommand)

For example:
```
python -m jupyter --help
```
shows me the full usage instructions for jupyter. 

So if you've installed jupyterlab then  `python -m jupyter lab` should work for you.

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one.

Thanks everyone and happy hacking! :bowtie:
