### ISSUE TITLE
4.7 release

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter_core#205]
@kevin-bates and I are hoping to release 4.7 next week (the week of Nov 2, 2020).

- [x] Review/merge #203 to fix backwards incompatibility
- [x] Review/merge #204 to update changelog
- [x] @kevin-bates release 4.7.0rc0 (update version.py to `VersionInfo(4, 7, 0, 'candidate', 0)`)
- [x] Release 4.7.0 final after a few days for feedback

**Comment by kevin-bates** [comment]
4.7.0rc0 is available on [pypi.org](https://pypi.org/project/jupyter-core/4.7.0rc0/).

**Comment by jasongrout** [comment]
Changelog at https://jupyter-core.readthedocs.io/en/latest/changelog.html#id1

**Comment by jasongrout** [comment]
Finally, after all these years!

```
% jupyter --paths
config:
    /[snip]/miniforge3/envs/devjlab/etc/jupyter
    /[snip]/.jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /[snip]/miniforge3/envs/devjlab/share/jupyter
    /[snip]/Library/Jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /[snip]/Library/Jupyter/runtime
```

**Comment by jasongrout** [comment]
I've been running this with the new environment variable defined, and have not noticed any problems. There has been no other feedback that I'm aware of. Perhaps we're good for a release?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-core-4-7-release-candidate/6728/1

**Comment by jasongrout** [comment]
I posted on Discourse, and said we hoped to make a release next week, and asked people to test and give feedback here. So perhaps we can plan to make a release next Tuesday or Wednesday?

**Comment by jasongrout** [comment]
Perhaps we can make a release now? I haven't heard any more feedback, blocking or otherwise.

**Comment by jasongrout** [comment]
@kevin-bates - I don't have permission to do this - can you make a release sometime this week, or give me permissions on pypi to make a release?

**Comment by kevin-bates** [comment]
Hi @jasongrout - I'm not authorized to manage users on the pypi project.  I'll spend time on this today.

Since rc0 has had no changes, this is really just a matter of applying a 4.7.0 tag to the rc0 tag and uploading the appropriately built artifacts to pypi - correct?

**Comment by kevin-bates** [comment]
Nevermind, there will need to be an update/commit the 4.7.0-tagged version.py file.

**Comment by jasongrout** [comment]
Yes, the version.py file needs to be updated as well.

**Comment by kevin-bates** [comment]
Done: https://pypi.org/project/jupyter-core

Thanks Jason!

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
Can you upload the source distribution too, the .tar.gz (from the `sdist`)? conda-forge uses the `.tar.gz`, not the wheel.

**Comment by kevin-bates** [comment]
Done.  Sorry about that.  I'm so used to just building the wheel.
