### ISSUE TITLE
Creating Jupyter Notebook Failed. An error occurred while creating a new notebook. Validation error: nbformat_minor

### ISSUE THREAD

**Issue by jwrth** [jupyter/jupyter_core#210]
Hi, everyone! When I want to create a new file Jupyter gives me the error shown in the following image. Does anybody have an idea what's the reason for it and how I can change it?

I'm not sure if it's connected but the error appears since I tried to export a notebook as html. I tried this first using "File - Download as..." but this gave me an error. It worked then in the terminal using "jupyter nbconvert -to html file.ipynb" but since I did this the validation error appears when I want to create a new file:

![grafik](https://user-images.githubusercontent.com/76480183/102889819-9fe17e00-445b-11eb-9ec8-46c3784f6d39.png)

I get a similar error when I try to work on notebooks that were created before:

![grafik](https://user-images.githubusercontent.com/76480183/102891373-5cd4da00-445e-11eb-9371-a573f4555545.png)

There I managed to solve the error by changing the value for "nbformat_minor" to 4 instead of 2 using a text editor. Therefore, I think the problem lies somehow in this nbformat_minor setting which is set to 2 instead of 4 when I create a new notebook. But I have no idea why this error appears now. I didn't update anything before this error appeared. Is there a way to change the default setting for nbformat_minor? The installed nbformat version is 5.0.8.

Would be great if anybody could help me out with that! Thanks a lot in advance!

Please let me know if you need any additional information!

**Comment by jwrth** [comment]
I guess it's helpful for you to know all the versions. Here's the result of pip freeze:

`alabaster==0.7.12
AmpUMI==1.0.0
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
anndata==0.7.4
anndata2ri==1.0.5
annoy==1.16.3
appdirs==1.4.4
argh==0.26.2
argon2-cffi==20.1.0
asn1crypto @ file:///home/conda/feedstock_root/build_artifacts/asn1crypto_1588618038116/work
astroid @ file:///home/conda/feedstock_root/build_artifacts/astroid_1591645081755/work
astropy==4.0.1.post1
atomicwrites @ file:///home/conda/feedstock_root/build_artifacts/atomicwrites_1588182545583/work
attrs==19.3.0
autopep8 @ file:///home/conda/feedstock_root/build_artifacts/autopep8_1591017828430/work
Babel==2.8.0
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1589761456552/work
bioservices==1.7.6
bitarray @ file:///home/conda/feedstock_root/build_artifacts/bitarray_1594039665500/work
bkcharts==0.2
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1588608214987/work
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1592869573618/work
boto==2.49.0
Bottleneck==1.3.2
brotlipy==0.7.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1593623337153/work
clyent==1.2.2
colorama==0.4.3
colorlog==4.1.0
conda==4.9.0
conda-build==3.19.2
conda-package-handling==1.6.0
conda-verify==3.1.1
contextlib2==0.6.0.post1
cryptography==2.9.2
cutadapt==2.10
cycler==0.10.0
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1591799499719/work
cytoolz==0.10.1
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1593753420471/work
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20181111
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1593754191641/work
dnaio==0.4.2
docutils==0.16
easydev==0.9.38
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1589994591731/work
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1591898334868/work
Flask==1.1.2
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1589989738418/work
future==0.18.2
fuzzywuzzy==0.18.0
get-version==2.1
gevent @ file:///home/conda/feedstock_root/build_artifacts/gevent_1592657467591/work
glob2==0.7
gmpy2==2.1.0b1
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1591368821264/work
grequests==0.6.0
h5py==2.10.0
HeapDict==1.0.1
html5lib @ file:///home/conda/feedstock_root/build_artifacts/html5lib_1592930327044/work
hypothesis @ file:///home/conda/feedstock_root/build_artifacts/hypothesis_1593564453829/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
imagecodecs @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs_1593295475914/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1594044661732/work
imagesize==1.2.0
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1593211369179/work
intervaltree==3.0.2
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1593978560801/work/dist/ipykernel-5.3.1-py3-none-any.whl
ipyparallel==6.3.0
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1592619900914/work
jeepney==0.4.3
Jinja2==2.11.2
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1593624380152/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1591810480056/work
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1593562235049/work
jupyter-console==6.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==2.1.5
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1593951277307/work
jupyterthemes==0.20.0
kb-python==0.24.1
keyring @ file:///home/conda/feedstock_root/build_artifacts/keyring_1588433935863/work
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
legacy-api-wrap==1.2
leidenalg==0.7.0
lesscpy==0.14.0
libarchive-c==2.9
lief==0.9.0
llvmlite==0.33.0+1.g022ab0f
locket==0.2.0
logomaker==0.8
loompy==3.0.6
louvain==0.6.1
lxml @ file:///home/conda/feedstock_root/build_artifacts/lxml_1589927514031/work
MarkupSafe==1.1.1
matplotlib==3.3.2
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
mock @ file:///home/conda/feedstock_root/build_artifacts/mock_1588618847833/work
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1592197792446/work
mpmath==1.1.0
msgpack==1.0.0
MulticoreTSNE==0.1
multipledispatch==0.6.0
NaiveDE==1.2.0
natsort==6.0.0
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.8
networkx==2.4
nltk==3.4.4
nose==1.3.7
notebook==6.1.5
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1594008868297/work
numexpr==2.7.1
numpy==1.18.5
numpy-groupies==0+unknown
numpydoc @ file:///home/conda/feedstock_root/build_artifacts/numpydoc_1593656006205/work
olefile==0.46
opencv-python==4.4.0.46
openpyxl @ file:///home/conda/feedstock_root/build_artifacts/openpyxl_1593690790606/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1589925210001/work
pandas @ file:///home/conda/feedstock_root/build_artifacts/pandas_1592421991297/work
pandocfilters==1.4.2
parso==0.7.0
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
physt==0.4.10.1
pickleshare==0.7.5
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1593694121332/work
Pint @ file:///home/conda/feedstock_root/build_artifacts/pint_1593714927369/work
pkginfo==1.5.0.1
plotly==4.4.1
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1592827471208/work
ply==3.11
progress-reporter==2.0
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1590412252446/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1592500439797/work
psutil==5.7.0
ptyprocess==0.6.0
py @ file:///home/conda/feedstock_root/build_artifacts/py_1593088446458/work
pybiomart==0.2.0
pycodestyle @ file:///home/conda/feedstock_root/build_artifacts/pycodestyle_1589305246696/work
pycosat==0.6.3
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pycrypto==2.6.1
pycurl==7.43.0.5
pydiffmap==0.2.0.1
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
pylint @ file:///home/conda/feedstock_root/build_artifacts/pylint_1592404303629/work
pyodbc==4.0.30
pyOpenSSL==19.1.0
pyparsing==2.4.7
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyrsistent==0.16.0
pysam==0.15.4
PySocks==1.7.1
pytest==5.4.3
pytest-arraydiff==0.3
pytest-astropy==0.7.0
pytest-astropy-header==0.1.2
pytest-doctestplus @ file:///home/conda/feedstock_root/build_artifacts/pytest-doctestplus_1591908454504/work
pytest-openfiles @ file:///home/conda/feedstock_root/build_artifacts/pytest-openfiles_1591909410901/work
pytest-remotedata==0.3.1
python-dateutil==2.8.1
python-igraph==0.8.0
python-jsonrpc-server @ file:///home/conda/feedstock_root/build_artifacts/python-jsonrpc-server_1588783985962/work
python-language-server @ file:///home/conda/feedstock_root/build_artifacts/python-language-server_1593716034648/work
python-Levenshtein==0.12.0
pytz==2020.1
PyWavelets==1.1.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==19.0.1
QDarkStyle==2.8.1
QtAwesome @ file:///home/conda/feedstock_root/build_artifacts/qtawesome_1588715536397/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole_1592845750760/work
QtPy==1.9.0
ReaDDy==2.0.2
regex==2020.7.14
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1592425495151/work
requests-cache==0.5.2
retrying==1.3.3
rope @ file:///home/conda/feedstock_root/build_artifacts/rope_1588950285934/work
rpforest==1.6
rpy2==3.3.6
Rtree==0.9.4
ruamel-yaml==0.15.80
scanpy==1.6.0
scikit-image==0.17.2
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1592502882224/work
scipy @ file:///tmp/build/80754af9/scipy_1592930510235/work
scrublet==0.2.1
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-base_1591878760859/work
SecretStorage==3.1.2
Send2Trash==1.5.0
seqlogo @ file:///opt/conda/conda-bld/seqlogo_1592931666104/work
setuptools-scm==4.1.2
Shapely==1.7.0
simplegeneric==0.8.1
sinfo==0.3.1
singledispatch==3.4.0.3
sip==4.19.23
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
sklearn==0.0
snowballstemmer==2.0.0
sortedcollections @ file:///home/conda/feedstock_root/build_artifacts/sortedcollections_1591583091437/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1591999956871/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1589778966114/work
SpatialDE==1.1.3
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1593947940626/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-websupport_1593344032344/work
spyder==3.3.6
spyder-kernels==0.5.2
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1593116989295/work
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1591963256838/work
stdlib-list==0.7.0
suds-jurko==0.6
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1593716797971/work
tables==3.6.1
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
texttable==1.6.2
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1593913740982/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1589469402899/work
toolz==0.10.0
tornado==6.0.4
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1593390011681/work
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1588470653596/work
tzlocal==2.1
ujson==1.35
umap-learn==0.3.10
unicodecsv==0.14.1
urllib3==1.25.9
watchdog @ file:///home/conda/feedstock_root/build_artifacts/watchdog_1593120501703/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1592931742287/work
webencodings==0.5.1
weblogo==0.0.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer==2.0.0
xlrd==1.2.0
XlsxWriter @ file:///home/conda/feedstock_root/build_artifacts/xlsxwriter_1590799523302/work
xlwt==1.3.0
xmltodict==0.12.0
xopen==0.8.4
yapf==0.29.0
zict==2.0.0
zipp==3.1.0
zope.event @ file:///home/conda/feedstock_root/build_artifacts/zope.event_1591372894284/work
zope.interface==5.1.0`

**Comment by rgbkrk** [comment]
Did you end up figuring this one out?

**Comment by jwrth** [comment]
@rgbkrk I didn't really find out what caused the error but a reinstallation of juypter helped in the end.
