### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: showing this error when importing excel file into jupyter

### ISSUE THREAD

**Issue by nikhileswarareddy9** [jupyter/jupyter_core#220]

**Comment by jasongrout** [comment]
FileNotFound errors is not typically an error from the Jupyter core repo. What leads you to think this is an error in Jupyter core? Does the traceback show the error is coming from this package?

**Comment by jasongrout** [comment]
Please post a more comprehensive error report, including code, instructions for reproducing it, and the full error traceback text.
