### ISSUE TITLE
Jupyter eco-system compatibility whish for "pypy3.7-v7.3.5-win64"

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyter_core#229]
Pywin32 doesn't compile on PyPy3 for Windows, as too big/tricky/whatever.

Would it be possible to replace pywin32 for the few functions you call using only  ctypes ?

https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py#L387.L403

Apparently, it seems the only [known]  blocker to get a jupyter notebook working on "pypy3.7-v7.3.5-win64", [from Jupyter side](https://github.com/jupyter/jupyter_core/issues/226)

**Comment by stonebig** [comment]
I confirm it is the only [remaining] blocker to get a jupyter notebook working on "pypy3.7-v7.3.5-win64"

**Comment by stonebig** [comment]
If anaconda is considering a PyPy3 64 bit on Windows, won't they have the problem too ?

**Comment by minrk** [comment]
closed by #230
