### ISSUE TITLE
"Download as" yields HTML files

### ISSUE THREAD

**Issue by ericmjl** [jupyter/jupyter_core#24]
I have tried downloading my code as `.py` and `.md`. In Safari, they both download as HTML files. Not quite sure what's going on here - I have IPython 3.1.0 (with notebook) installed. Might you guys have an idea?

**Comment by takluyver** [comment]
Can you reproduce it in another browser?

**Comment by ericmjl** [comment]
My other browsers tested were Firefox and Chrome (sorry for the delay). Firefox works with no problems. As with Chrome.

**Comment by takluyver** [comment]
No problem. Since this is something specific to Safari, I'll let one of the Mac users debug it.

**Comment by Carreau** [comment]
Seem to be webkit specific, people complain about that all over the internet. Apparently it is possible to work around by some weird combinaison of headers which are technically correct, but not really, like saying that a .py is `octet/stream`.

**Comment by takluyver** [comment]
I don't think we've heard from many other users with this issue, so I'm guessing it got fixed somehow, either by us or by Safari. If it's still a problem, please open a new issue on the jupyter/notebook repo (that's the part that deals with all the HTTP stuff).
