### ISSUE TITLE
New patch release with https://github.com/jupyter/jupyter_core/pull/271

### ISSUE THREAD

**Issue by trungleduc** [jupyter/jupyter_core#274]
Hello, we are bumping `jupyter_server` in `Voila` to `1.18`  to get the security fixes but then `Voila`  can not serve some files on Windows. This issue can be fixed by  https://github.com/jupyter/jupyter_core/pull/271.
Is there any plan for a patch release soon?

**Comment by blink1073** [comment]
Cutting a release now

**Comment by blink1073** [comment]
https://github.com/jupyter/jupyter_core/releases/tag/4.11.0

**Comment by trungleduc** [comment]
Thanks!
