### ISSUE TITLE
Jupyter Core 5.0 Major Release

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter_core#284]
We have a few issues that would require a major release. This issue coordinates work for a 5.0 major release

See the project board for issue tracking for 5.0: https://github.com/orgs/jupyter/projects/6

- Also https://github.com/jupyter/jupyter_core/issues/228 looks good to tackle, which probably does not require a major release.

**Comment by blink1073** [comment]
https://pypi.org/project/jupyter-core/5.0.0rc1/ fixes the version handling in `version.py`.

**Comment by fcollonval** [comment]
I would like to highlight the comments https://github.com/jupyter/jupyter_core/pull/291#issuecomment-1262498164

In particular what should we do about the lab configuration? If the configuration starts to be in CWD by default, lots of user will have a hard time figuring out
- why their settings are not loaded any longer or are inconsistent
- and as pointed by @kevin-bates why the config folder is visible

**Comment by blink1073** [comment]
After [5.0.0rc2](https://github.com/jupyter/jupyter_core/releases/tag/5.0.0rc2), the cwd is no longer included at all.  @kevin-bates can you please see if you're getting the same behavior?

**Comment by kevin-bates** [comment]
@blink1073 - `jupyter_core==5.0.0rc2` no longer creates the `lab/workspaces` folder in the user's home directory when invoking Lab from that directory ([per my previous observation](https://github.com/jupyter/jupyter_core/pull/291#issuecomment-1265747603)).  I also reconfirmed the issue using `5.0.0rc1`.

**Comment by blink1073** [comment]
Great, thanks!

**Comment by blink1073** [comment]
I plan to make the release tomorrow, with the release notes [here](https://github.com/jupyter/jupyter_core/issues/294#issuecomment-1306320042).

**Comment by blink1073** [comment]
Closing as complete
