### ISSUE TITLE
5.0 changelog

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter_core#294]
We have several large changes coming in 5.0, and I think we should have a changelog that elaborates on the changes more. This issue is for expanding the changelog to include a discussion about how to migrate and use the new features.

We should probably also add mention of the new platformdirs environment variable to the documentation of various functions in paths, like we already mention the prefer env variable.

**Comment by blink1073** [comment]
## Major Changes

### Prefer Environment Level Configuration
We now make the assumption that if we are running in a virtual environment, we should prioritize the environment-level `sys.prefix` over the user-level paths. Users can opt out of this behavior by setting `JUPYTER_PREFER_ENV_PATH`, which takes precedence over our autodetection.

### Migration to Standard Platform Directories
In version 5, we introduce a `JUPYTER_PLATFORM_DIRS` environment variable to opt in to using more appropriate platform-specific directories.  We raise a deprecation warning if the variable is not set.  In version 6,  `JUPYTER_PLATFORM_DIRS` will be opt-out.  In version 7, we will remove the environment variable checks and old directory logic.

### Drop Support for Python 3.7
We are dropping support for Python 3.7 ahead of its official end of life, to reduce maintenance burden as we add support for Python 3.11.
