### ISSUE TITLE
jupyter_core package requires invalid pywin32 version

### ISSUE THREAD

**Issue by andy-maier** [jupyter/jupyter_core#346]
The jupyter_core package requires pywin32>=1.0 (on win32)

However, pywin32 has integer version numbers from 210 to 305.

I would actually assume that this error does not cause any problems because I would expect pip to interpret e.g. 227 to be larger than 1.0, but we actually get a pip conflict error with this:

```
The conflict is caused by:
    jupyter-core 4.7.0 depends on pywin32>=1.0; sys_platform == "win32"
    The user requested (constraint) pywin32==227
```
Github Actions log file: https://github.com/zhmcclient/python-zhmcclient/actions/runs/4382402211/jobs/7671412008

jupyter-core started introducing the dependency to pywin32 in its version 4.6.0 and there it was already incorrect (i.e. with pywin32>=1.0)

I assume that the problem above can also be solved in the dependencies and minimum constraints in our project (after all it only showed up when I was increasing some minimum versions), or possibly by using a different pip version, but nevertheless the version requirement to pywin32 in this project here should be fixed, IMO.

**Comment by blink1073** [comment]
Thanks for the report!  Addressing in #347.
