### ISSUE TITLE
Regression: Error when config dir is readonly (Worked before)

### ISSUE THREAD

**Issue by jschaeck** [jupyter/jupyter_core#378]
Hello, 

in our hosted system, the jupyter config dir is ready only to ensure that users are not messing up with it.
This worked nicely for quite some time (in between we had to add a marker file "migrated" but since then worked fine again).

Now with a recent version of jupyter-core this breaks unfortunately. 

Error message is:

```
File ".../site-packages/jupyter_core/application.py", line 168, in migrate_config
    f_marker = open(os.path.join(self.config_dir, "migrated"), "r+")  # noqa
OSError: [Errno 30] Read-only file system: '/config/xyz/migrated'
```

I think this regression came in with https://github.com/jupyter/jupyter_core/pull/356/files (See changes below where exists check was changed to open with "r+"

I think the editor planned for this with the         

```
except PermissionError:  # not readable and/or writable
       return  # so let's give up migration in such an environment
```

but in case of the read only file system (at least in our case)

that is an OSError, not an PermissionError

Request: Can the PermissionError handling be applied to OSError as well?

![image](https://github.com/jupyter/jupyter_core/assets/12323010/41c4b8f9-5917-49a3-b2c0-368b3d1e45f1)

**Comment by jschaeck** [comment]
@blink1073 Hi, sorry to tag you directly but from the commit history you are the person that performed the most changes and I thought I maybe run this by you. Any thoughts here?

**Comment by blink1073** [comment]
Thanks for the heads up @jschaeck, I'll make a release with #379 early next week.
