### ISSUE TITLE
Is setup.py develop not supported on purpose?

### ISSUE THREAD

**Issue by danielballan** [jupyter/jupyter_core#43]
I'm as unenthused about setuptools as the next person, but develop installs are nice. Did you prohibit them for a reason?

**Comment by Carreau** [comment]
try `pip install -e .`

**Comment by danielballan** [comment]
Oh, neat. Thanks @Carreau. For the sake of my own projects, is there a reason for using setuptools in some cases (e.g., notebook) and not others?

**Comment by Carreau** [comment]
Setuptools [is evil](https://bitbucket.org/pypa/setuptools/pull-requests/135/remove-import-sys-from-easy-installpth/diff).

Personally for pure python lib I use @takluyver's [flit](https://flit.readthedocs.org).

`Pip install -e .` should work in  all our repos . 

Closing if it works :-)

**Comment by danielballan** [comment]
Yep, all's well. Thanks again, buddy.
