### ISSUE TITLE
Changing the Location of the Jupyter Config Directory

### ISSUE THREAD

**Issue by startakovsky** [jupyter/jupyter_core#46]
I might be missing something, but I do not know how to modify the location of the Jupyter Config directory.

Before "The Big Split" I had my .ipython `$IPYTHONDIR` set to a single location accessible from multiple machines, not having to duplicate the location of templates.

Today I spun up a brand new Ubuntu 14.04 box, set the environmental variable described above and installed Jupyter on it, the latest release. 

On the first run of `jupyter notebook` those config files were copied (PASTED BELOW), and from that point Jupyter ignores the files in `$IPYTHONDIR` from that point forward.

Would love to either be 1) pointed to the appropriate docs to change the location of `jupyter --config-dir` from it's default location 2) or get some idea of an ETA for this functionality to be available or 3) tell me how to hack it so I can put the config files anywhere I want, which may very well include some option when running `jupyter notebook` to copy config files again. Seems like that might be the easiest implementation.

Here's an output of the various paths Jupyter users. I'm interested in modifying the location of the first path in the "config" key below.

    {  
       "data":[  
          "/home/vagrant/.local/share/jupyter",
          "/usr/local/share/jupyter",
          "/usr/share/jupyter"
       ],
       "runtime":[  
          "/run/user/1000/jupyter"
       ],
       "config":[  
          "/home/vagrant/.jupyter",
          "/usr/etc/jupyter",
          "/usr/local/etc/jupyter",
          "/etc/jupyter"
       ]

----output of first run of JUPYTER NOTEBOOK: copying config files from $IPYTHONDIR...---

vagrant@vagrant-ubuntu-trusty-64:~$ jupyter notebook
    [I 18:24:24.761 NotebookApp] Copying /vagrant/.ipython/profile_default/security/notebook_secret -> /home/vagrant/.local/share/jupyter/notebook_secret
    [I 18:24:24.768 NotebookApp] Copying /vagrant/.ipython/profile_default/nbconfig -> /home/vagrant/.jupyter/nbconfig
    [I 18:24:24.778 NotebookApp] Copying /vagrant/.ipython/nbextensions -> /home/vagrant/.local/share/jupyter/nbextensions
    [I 18:24:25.296 NotebookApp] Copying /vagrant/.ipython/profile_default/security/nbsignatures.db -> /home/vagrant/.local/share/jupyter/nbsignatures.db
    [I 18:24:25.301 NotebookApp] Copying /vagrant/.ipython/profile_default/security/notebook_cookie_secret -> /home/vagrant/.local/share/jupyter/notebook_cookie_secret
    [I 18:24:25.307 NotebookApp] Copying /vagrant/.ipython/profile_default/ipython_notebook_config.py -> /home/vagrant/.jupyter/jupyter_notebook_config.py
    [I 18:24:25.313 NotebookApp] Copying /vagrant/.ipython/profile_default/ipython_nbconvert_config.py -> /home/vagrant/.jupyter/jupyter_nbconvert_config.py
    [I 18:24:25.323 NotebookApp] Copying /vagrant/.ipython/profile_default/static/custom/custom.css -> /home/vagrant/.jupyter/custom/custom.css

**Comment by minrk** [comment]
The new dir is controlled by JUPYTER_CONFIG_DIR. [Docs are here](https://jupyter.readthedocs.org/en/latest/system.html#configuration).

**Comment by startakovsky** [comment]
Thanks @minrk, this helped. Because I'm trying to make the "big split" happen, I want to decouple `nbextensions` from my `$IPYTHONDIR` and add it to `$JUPYTER_CONFIG_DIR` instead.  Any tips there? Thanks!

**Comment by minrk** [comment]
Jupyter separates [**data files**](https://jupyter.readthedocs.org/en/latest/system.html#data-files) (nbextensions, kernelspecs) from [**runtime files**](https://jupyter.readthedocs.org/en/latest/system.html#runtime-files) (logs, pid files, connection files) from [**configuration**](https://jupyter.readthedocs.org/en/latest/system.html#configuration) (config files, custom.js). nbextensions go in the jupyter data files location, e.g. `~/.local/share/jupyter[/nbextensions]` or `/usr/local/share/jupyter[/nbextensions]`. The `jupyter migrate` command should take care of copying nbextensions to their new home. You can see where files will be found with `jupyter --paths`.

**Comment by startakovsky** [comment]
@minrk  Thank you so much! I am now completely on board with the big split.
