### ISSUE TITLE
zsh autocompletion file

### ISSUE THREAD

**Issue by anntzer** [jupyter/jupyter_core#47]
I have written a small zsh autocompletion file for jupyter, currently at http://pastebin.com/XW0nPWjG .
There seemed to be some interest in such a file for ipython (cf ipython/ipython#8767), but I guess it would make more sense to merge this into jupyter_core?
I haven't made this into a PR because I don't know where to put it in the source tree :-)

**Comment by Carreau** [comment]
Well if it works with jupyter, +1, though the completion will work even if subcommand not availlable ?

I would create a `/tools` or whatever folder with this in it. 

conda have a nice `conda install argcomplete` do we want something similar ?

**Comment by anntzer** [comment]
Good catch, I just wrote this for whatever commands got installed by `<linux-package-manager> install jupyter`.  A bit {la,bu}zy to test installing subcommands one at a time right now (I guess I can just `pip install jupyter_core && pip install <subcommand>` in a clean conda env?) but it should boil down to a bunch of `if which jupyter-$subcmd; then commands=($commands $subcmd_help); fi` in `_jupyter_cmds`.

**Comment by Carreau** [comment]
> A bit {la,bu}zy to test installing subcommands one at a time right now

Well I think it is fine if it completes and the subcommand is not availlable. It's not the end of the world, 
and you are likely to know which command are availlable anyway.

**Comment by anntzer** [comment]
fixed it.

**Comment by Carreau** [comment]
Closed by #48
