### ISSUE TITLE
check that tools/_jupyter zsh completion is packaged in setup.py

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter_core#49]
see #47 and #48

**Comment by minrk** [comment]
And it should probably be moved to somewhere like `examples/zsh_completions`

**Comment by rgbkrk** [comment]
I was going to comment in that PR about bash completions too. We could include these in a completions directory or even spit them out when requested by the client (the [`rack` cli does this](https://github.com/rackspace/rack#bash-completion), but it's using go code through codegangsta/cli for bash foo).
