### ISSUE TITLE
Should jupyter_core provide jupyter.py?

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyter_core#55]
It seems like juptyer_core should provide `jupyter.py` so that `python -m jupyter` works if any jupyter entrypoint is installed, rather than only when the metapackage has been used to install everything. This would conflict with the current behavior of the jupyter metapackage, which writes the same file, but with pip that doesn't actually matter, since the behavior of the file would be unchanged. I would propose the `jupyter` mpkg actually install an entirely unused jupyter_mpkg.py.

cc @fperez @takluyver @ellisonbg

**Comment by damianavila** [comment]
I would say yes...

**Comment by minrk** [comment]
closed by #70
