### ISSUE TITLE
add solekernel subcommand to jupyter command.

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_core#82]
I can't find a way to just start a kernel without using notebook or console/qtconsole.

The only way to start one and leave it there running is or to start notebook and go click,click,click, or to start qtconsole and exit with keep_kernel.

There is a  kernel manager?

I just want to find a way to start several kernels and keep them running in the background without the browser. I know that I can manage the kernels in the notebook server but can't find a way to run a new kernel in bash. am I blind regarding  the documentation?

**Comment by takluyver** [comment]
Currently there is a separate, and in most cases totally different, command to start each kernel. E.g. for IPython, you can use `ipython kernel`. The 'kernel nanny' proposal (jupyter/enhancement-proposals#14) will add a unified command to start any Jupyter kernel without a frontend.

**Comment by ocehugo** [comment]
Ahh...completely forgot to check ipython.

**Comment by rolweber** [comment]
So... is this issue resolved and can be closed?

**Comment by takluyver** [comment]
I think we're leaving it as a feature request for a unified command for starting different kinds of kernel - at present the command to start a kernel is specific to the implementation (and many kernels probably require a connection file to be written before launching them).

**Comment by takluyver** [comment]
`jupyter kernel` now exists to run a kernel through Jupyter without an interface. This is part of the jupyter_client repo.
