### ISSUE TITLE
Use jupyter command, It show error: No such file or directory

### ISSUE THREAD

**Issue by Anne623** [jupyter/jupyter_core#84]
Hi, All, 
     I download source code from git repo. I checkout tag `4.1.0`, and I install jupyter_core from source code to replace jupyter_core which installed by anaconda. while ,when I finished install, I try use `jupyter` command, it show error: 

```
: No such file or directory
```

Install jupyter_core from source code:

```
[root@linux-59 jupyter_core]# python setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
creating /usr/local/Python/lib/python2.7/site-packages/jupyter_core
copying build/lib/jupyter_core/__init__.py -> /usr/local/Python/lib/python2.7/site-packages/jupyter_core
....
....
byte-compiling /usr/local/Python/lib/python2.7/site-packages/jupyter_core/tests/dotipython/profile_default/ipython_config.py to ipython_config.pyc
byte-compiling /usr/local/Python/lib/python2.7/site-packages/jupyter_core/tests/dotipython/profile_default/ipython_console_config.py to ipython_console_config.pyc
byte-compiling /usr/local/Python/lib/python2.7/site-packages/jupyter_core/tests/dotipython/profile_default/ipython_kernel_config.py to ipython_kernel_config.pyc
byte-compiling /usr/local/Python/lib/python2.7/site-packages/jupyter_core/tests/dotipython/profile_default/ipython_notebook_config.py to ipython_notebook_config.pyc
byte-compiling /usr/local/Python/lib/python2.7/site-packages/jupyter_core/tests/test_paths.py to test_paths.pyc
running install_scripts
copying build/scripts-2.7/jupyter-migrate -> /usr/local/Python/bin
copying build/scripts-2.7/jupyter -> /usr/local/Python/bin
changing mode of /usr/local/Python/bin/jupyter-migrate to 755
changing mode of /usr/local/Python/bin/jupyter to 755
running install_egg_info
Writing /usr/local/Python/lib/python2.7/site-packages/jupyter_core-4.1.0-py2.7.egg-info
```

I use command:

```
[root@linux-59 jupyter_core]# /usr/local/Python/bin/jupyter
: No such file or directory
[root@linux-59 jupyter_core]# /usr/local/Python/bin/jupyter --h
: No such file or directory
```

Does some config i miss?

**Comment by takluyver** [comment]
Can you check that file does actually exist and is executable?

```
ls -l /usr/local/Python/bin/
```

**Comment by Anne623** [comment]
@takluyver Thank you for your reply, I check that file is exist and is executable.
```
[root@linux-59 ipykernel]# ls -l /usr/local/Python/bin/ | grep jupyter
-rwxr-xr-x 1 root root     145 Aug 17 10:35 jupyter
-rwxrwxr-x 1 root root     107 Aug 16 11:49 jupyter-console
-rwxr-xr-x 1 root root     173 Aug 17 10:33 jupyter-kernelspec
-rwxr-xr-x 1 root root     155 Aug 17 10:35 jupyter-migrate
-rwxrwxr-x 1 root root     112 Aug 16 11:49 jupyter-nbconvert
-rwxr-xr-x 1 root root     107 Aug 17 10:28 jupyter-nbextension
-rwxr-xr-x 1 root root     106 Aug 17 10:28 jupyter-notebook
-rwxrwxr-x 1 root root     111 Aug 16 11:49 jupyter-qtconsole
-rwxr-xr-x 1 root root     181 Aug 17 10:36 jupyter-serverextension
-rwxr-xr-x 1 root root     168 Aug 17 10:35 jupyter-trust
You have mail in /var/spool/mail/root
[root@linux-59 ipykernel]# chmod 777 /usr/local/Python/bin/*
[root@linux-59 ipykernel]# /usr/local/Python/bin/jupyter
: No such file or directory
[root@linux-59 ipykernel]# ls -l /usr/local/Python/bin/ | grep jupyter
-rwxrwxrwx 1 root root     145 Aug 17 10:35 jupyter
-rwxrwxrwx 1 root root     107 Aug 16 11:49 jupyter-console
-rwxrwxrwx 1 root root     173 Aug 17 10:33 jupyter-kernelspec
-rwxrwxrwx 1 root root     155 Aug 17 10:35 jupyter-migrate
-rwxrwxrwx 1 root root     112 Aug 16 11:49 jupyter-nbconvert
-rwxrwxrwx 1 root root     107 Aug 17 10:28 jupyter-nbextension
-rwxrwxrwx 1 root root     106 Aug 17 10:28 jupyter-notebook
-rwxrwxrwx 1 root root     111 Aug 16 11:49 jupyter-qtconsole
-rwxrwxrwx 1 root root     181 Aug 17 10:36 jupyter-serverextension
-rwxrwxrwx 1 root root     168 Aug 17 10:35 jupyter-trust
[root@linux-59 ipykernel]# /usr/local/Python/bin/jupyter
: No such file or directory
```

**Comment by takluyver** [comment]
Weird. What does the file contain? Does the first line start with `#!`?

**Comment by Anne623** [comment]
yes. the file content is 
```
#!/usr/bin/env python
"""Launch the root jupyter command"""

from jupyter_core.command import main

if __name__ == '__main__':
    main()
```

**Comment by takluyver** [comment]
And can you run `/usr/bin/env python`? I'm clutching at straws here, it all looks completely normal.

**Comment by Anne623** [comment]
yes, the pic is:
![image](https://cloud.githubusercontent.com/assets/10845504/17847289/c75fec12-687f-11e6-8386-0d821e0acd4a.png)

**Comment by takluyver** [comment]
And have you tried opening a new terminal?

**Comment by Anne623** [comment]
@takluyver  Yes , I open a new shell terminal. but it's the same error.

**Comment by takluyver** [comment]
Weird. What if you try:

```
/usr/bin/env python /usr/local/Python/bin/jupyter
```

**Comment by Anne623** [comment]
If I try ```/usr/bin/env python /usr/local/Python/bin/jupyter`` it works fine.

**Comment by takluyver** [comment]
Weird. Sorry, I'm all out of ideas for now.

**Comment by slonak79** [comment]
I'm having the same issue.
```
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
```

**Comment by takluyver** [comment]
Does `jupyter-notebook` work instead of `jupyter notebook`?

**Comment by darobin** [comment]
Getting the same thing, right from a fresh Anaconda install. Running `jupyter-notebook` works, as do `jupyter --help`, `jupyter --version`, `jupyter --paths`…

**Comment by Milannju** [comment]
Try this commend: 
python -m IPython notebook

**Comment by Milannju** [comment]
Try this commend: python -m IPython notebook

**Comment by th-walker** [comment]
@Milannju I had the same issue `python -m IPython notebook` worked for me - thanks.

**Comment by WalkerJG** [comment]
@ksr11 Thanks! I had the same problem, and your solution worked for me.

**Comment by davidwjx** [comment]
@Milannju  thaaaanks.
python -m IPython notebook  did work well for me in High Sierra 10.13.3.

**Comment by awelkie** [comment]
On Fedora 27 I had to install python3-notebook

```
dnf install python3-notebook
```

**Comment by eega** [comment]
Had the same issue on Ubuntu 17.10. `python3 -m IPython notebook` works, `sudo apt install jupyter-notebook` didn't change a thing for me.

**Comment by ynsrachana** [comment]
my jupyter path is 
jupyter --paths
config:
    /root/.jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /root/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /root/.local/share/jupyter/runtime
i can c d version of jupyter. but am getting d error as
    python_lib_contents = listdir("{0}/python/lib".format(self.spark_home))
FileNotFoundError: [Errno 2] No such file or directory: '/python/lib'

and checked the path /usr/local/python/bin but i dont have the python folder. /usr/local/bin itself.

**Comment by Pradeep119** [comment]
first install jupyter via  sudo apt install jupyter-notebook 
and use jupyter-notebook to run it

**Comment by takluyver** [comment]
We don't recommend installing through apt, because that will almost always be out of date. Even in Ubuntu 18.04, which was released a couple of days ago, it's not up to date.

**Comment by seva100** [comment]
@slonak79, I also encountered this problem eventually; for me it was easily solved by doing
`mkdir ~/.jupyter`
before executing other jupyter-related commands.

**Comment by przbatte** [comment]
Please try: `pip3 install jupyter --force` or `pip install jupyter --force`

**Comment by iamtodor** [comment]
`python -m IPython notebook ` - worked for me. however I got the following output while executing `jupyter-notebook` or `jupyter notebook`:
```
mcbk:machine-learning todor$ jupyter-notebook
-bash: /usr/local/bin/jupyter-notebook: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory
mcbk:machine-learning todor$ jupyter notebook
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
```

**Comment by hemangjoshi37a** [comment]
It seems to me as though the installation has messed up somehow. Try running:

# For Python 2
pip install --upgrade --force-reinstall --no-cache-dir jupyter
# For Python 3
pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
This should reinstall everything from PyPi. This should solve the problem as I think running pip install "ipython[notebook]" messed things up.

**Comment by mehraanuj** [comment]
I was getting this issue. I did following steps-

1. Reset your configuration file.
2. try command jupyter notebook --allow-root   (Remember to give space after notebook)

It worked!

**Comment by aniketjha1729** [comment]
open ur terminal type: #-r
after that type jupyter notebook
THis will fix ur problem

**Comment by matteocollina** [comment]
@takluyver it works for Ubuntu 18.04

**Comment by BigZSmallY** [comment]
> IPython

It works for me too.

**Comment by Adnan0208** [comment]
> Try this commend: python -m IPython notebook

Ahh...this command worked for me. I was searched a lot on this and finally to uninstall everything and want to do it again with installation of Anaconda. But saved! Thanks a lot.

**Comment by BasharAlmomaine** [comment]
> python -m IPython notebook

Where to use it?

**Comment by kevin-bates** [comment]
>> python -m IPython notebook

> Where to use it?

You would use this from a terminal window - although I don't think that answers your question.  Please note that use of `IPython` to run a notebook is a bit outdated and the more current command would be `python -m jupyter notebook`.

Are you asking because you're getting `No such file` issues when running `jupyter`? 
Could you provide information relative to your issue?  
Could you provide the output of `jupyter troubleshoot`?

**Comment by BasharAlmomaine** [comment]
> python -m jupyter notebook

Greetings, 
Thank you for your concern.
I tried to write this code" python -m jupyter notebook " in the terminal but with no solution, I still have the same results.
yes, I am asking about the no file issue when running in jupytur.
Please see the 2 attachments below regarding the issue whenever I run the code.

![image](https://user-images.githubusercontent.com/81293542/115135921-15c5b280-a014-11eb-8087-3126a1a25fff.png)
![image](https://user-images.githubusercontent.com/81293542/115135923-1bbb9380-a014-11eb-9598-c627253bb7a8.png)

**Comment by BasharAlmomaine** [comment]
it's ok. thanks for the help.
I figured it out and fixed it.
I just opened the excel file and saved it as CSV( Comma delimited).

**Comment by ivanov** [comment]
Hey there, I'm going through old issues and it seems to me that it makes sense to close this one. Other than the unrelated simple FileNotFound error posted within the last month, this issue did not have any activity for the past 2 years. It looks like most folks who ran into this were using a mix of packages that shipped with their distribution or conda and pip. Hopefully anyone who runs into this can try some of the workarounds proposed here.

Thanks everyone and happy hacking! :bowtie:
