### ISSUE TITLE
Fix and/or bump jupyter-1.0.0 at pypi

### ISSUE THREAD

**Issue by holgersson32644** [jupyter/jupyter_core#85]
Hello,

currently we run into file collisions at gentoo**[1]**, because #55 moved the jupyter.py file without updating it “downstream“ (a.k.a pypi.python.org). Could you please fix that?

**[1]** https://bugs.gentoo.org/show_bug.cgi?id=589750

**Comment by takluyver** [comment]
jupyter/jupyter#198 would remove the file from the 'jupyter' metapackage. Downstream packagers are also welcome to create their own 'jupyter' metapackage directly - it's only there as a shortcut to install several packages.
